use strict;
use warnings;

use MojoX::HyperScript qw[ H ];
use Test2::Bundle::More;

my $dom = H 'p.classA' => { id => 'msg' }, (
  q{hello, world!},
  H 'br',
  H em => ['this message is generated by MojoX::HyperScript'],
);

ok($dom);

is( $dom->attr('id'), 'msg' );
is( $dom->attr('class'), 'classA' );

is( $dom->at('br')->tag, 'br' );
is( $dom->at('em')->text, 'this message is generated by MojoX::HyperScript' );

is( $dom->text, 'hello, world!' );

done_testing;
